### PR TITLE
Workflow for Windows, Linux and MacOS building.

### PR DESCRIPTION
**Pull request by josephmoresena**

### CODE REVIEW

**Comment by teobugslayer** [comment]
Hi @josephmoresena, considering that the official release of 6.0 is in like 4 working days, I suggest to rework the workflow to be based on .net 6.0. Considering that this project is both a sample and a template for starting a new projects, I think it is a good practice to use the latest stable .NET release, and 6.0 would be this release in just few days. Opinions?

**Comment by josephmoresena** [comment]
> Hi @josephmoresena, considering that the official release of 6.0 is in like 4 working days, I suggest to rework the workflow to be based on .net 6.0. Considering that this project is both a sample and a template for starting a new projects, I think it is a good practice to use the latest stable .NET release, and 6.0 would be this release in just few days. Opinions?

That seems very good to me! I will make the change to include version 6.0 in the project and in the workflow.

**Comment by josephmoresena** [comment]
I had to leave Avalonia UI 0.10.8 instead of the latest one because at clicking on the menu option, it closes automatically in macOS. However when I press alt, the menu option opens and allows to access its functions.

**Comment by josephmoresena** [comment]
Avalonia issue: https://github.com/AvaloniaUI/Avalonia/issues/6888

**Comment by josephmoresena** [comment]
Added Multi Theme support.

**Comment by josephmoresena** [comment]
> Added Multi Theme support.

Fix Fluent theme with Trimming link enable. https://github.com/AvaloniaUI/Avalonia/issues/7075

**Comment by josephmoresena** [comment]
Closed to make improvements for macOS

**Pull request closed without merging**
