### PR TITLE
Update to Avalonia 11 with some AOT improvements 

### PR DESCRIPTION
**Pull request by maxkatz6**
It is possible to get avalonia app running without any special AOT configuration now and without RD files:
1. Use Avalonia11
2. Use Compiled Bindings (instead of default reflection bindings)

Almost everything can be done using latest "preview4" nuget build, but I targeted this PR specifically as it removes the need of RD file: https://github.com/AvaloniaUI/Avalonia/pull/9413

Only one thing that doesn't work, as I tested - menus. Probably related to Windows Automation API which uses COM. Need somebody to test on macOS, should be better there.

Other minor changes:
1. Use IAssetLoader instead of manual assembly resources lookup
2. Use SimpleTheme class instead of multiple StyleInclude for the simple (formally "default") theme.
3. Change Theme.Mode property instead of replacing resources, as it is faster.
4. No need for "macos" main window, as NativeMenu works on windows too with a help of NativeMenuBar control.

### CODE REVIEW

**Comment by maxkatz6** [comment]
@teobugslayer @josephmoresena if you are interested.
When Windows Automation API COM issue is solved, it seems Avalonia will work with AOT just out of the box.

**Comment by josephmoresena** [comment]
I was experimenting with Avalonia 11 but I think is better maintain another branch only for Avalonia 11 (at least until its stable version).

**Review by josephmoresena — COMMENTED** [review]
Would you try to use DataGrid control on About window instead of ScrollViewer?

**Comment by maxkatz6** [comment]
@josephmoresena good idea. I also added a button below the menu, so it's possible to open this window on windows, where menus do not work with AOT now.

**Comment by josephmoresena** [comment]
@maxkatz6 please update test.cmd, test.sh and test.command with the new framework version or translate all of batches logic to a build action (MSBuild).

**Comment by josephmoresena** [comment]
> 4. No need for "macos" main window, as NativeMenu works on windows too with a help of NativeMenuBar control.

I can't test right now in osx, in a couple next day I will. 

> Only one thing that doesn't work, as I tested - menus. Probably related to Windows Automation API which uses COM. Need somebody to test on macOS, should be better there.

On both Windows and Linux, I've seen the menu bar but I was unable to open any items. I don't think it's related to COM, at least not on Linux.

**Comment by josephmoresena** [comment]
There are problems with themes:
* Application closes attempted to open About Windows with simple light theme.
* Menu bar looks very weird one after simple light theme is using.
* Simple dark theme is not working.
* Fluent dark theme shouldn't have a full-black background, should it?

**Comment by maxkatz6** [comment]
> Application closes attempted to open About Windows with simple light theme.

Right, forgot that we have two different themes here. I have included only Fluent theme datagrid styles,

> Menu bar looks very weird one after simple light theme is using.

In what weird? I saw there is a bottom and top scrollers appearing when shouldn't, but aside from that seems correct.

> Simple dark theme is not working.

Theme switching isn't supported in runtime (from fluent to simple or another way). Only theme variants (modes) are supported. For the demo project it needs to be rethinked.

> Fluent dark theme shouldn't have a full-black background, should it?

It always was black IIRC.

**Comment by josephmoresena** [comment]
> In what weird? I saw there is a bottom and top scrollers appearing when shouldn't, but aside from that seems correct.

Like that (the space between menu options):
SimpleLight

> > Simple dark theme is not working.
> 
> Theme switching isn't supported in runtime (from fluent to simple or another way). Only theme variants (modes) are supported. For the demo project it needs to be rethinked.

Ohh I see. Is possible have two App classes, one for Simple and one for Fluent? The switching may implies a different invocation method or an application restart.

> > Fluent dark theme shouldn't have a full-black background, should it?
> 
> It always was black IIRC.

Please review my branch for theme support, it may help https://github.com/josephmoresena/AvaloniaCoreRTDemo/tree/avalonia11. At least SimpleTheme has a dark-gray background.

**Comment by maxkatz6** [comment]
> Ohh I see. Is possible have two App classes, one for Simple and one for Fluent? The switching may implies a different invocation method or an application restart.

Reopening the window should be enough for the demo app.

>  At least SimpleTheme has a dark-gray background.

Yes, simple one has a gray background. Fluent one has a black background same as it was in UWP/WinUI.

**Comment by teobugslayer** [comment]
The interesting problem is what to do to accommodate people who want to use older version of Avalonia (why would they?).

Maybe I'll do a release with the current version and then merge your PR, but if you have better ideas, please share.

**Comment by josephmoresena** [comment]
@teobugslayer we need update framework version for github actions.

**Comment by teobugslayer** [comment]
@maxkatz6, can you please resolve the conflicts and update the PR?

**Comment by teobugslayer** [comment]
Looks like the macOS build is failing. Can anyone with access to a mac check it out, please?

**Pull request merged**
